spin_manifest_version = "1"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = ""
name = "k8s-spin-webhooks"
trigger = { type = "http", base = "/webhooks" }
version = "0.1.0"

[variables]
shared_access_key = { default = "" }

[[component]]
id = "thumbnail"
source = "thumbnail/thumbnail.wasm"
allowed_http_hosts = ["jpfluegerc0f2.blob.core.windows.net"]
[component.trigger]
route = "/thumbnail"
[component.build]
workdir = "thumbnail"
command = "tinygo build -target=wasi -gc=leaking -no-debug -o thumbnail.wasm main.go"
watch = ["main.go", "blob/blob.go", "go.mod"]
[component.config]
shared_access_key = "{{ shared_access_key }}"
