name: release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'
jobs:
  release:
    permissions:
      contents: write
      packages: write
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set RELEASE_VERSION ENV var
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: lowercase the runner OS name
        shell: bash
        run: |
          OS=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
          echo "RUNNER_OS=$OS" >> $GITHUB_ENV

      # Setup buildx to build multiarch image: https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: setup buildx
        uses: docker/setup-buildx-action@v2

      - name: login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push webhooks app
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/jpflueger/k8s-spin-demo/webhooks:${{ env.RELEASE_VERSION }}
            ghcr.io/jpflueger/k8s-spin-demo/webhooks:latest
          context: webhooks
          platforms: wasi/wasm

      - name: clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json